import { createFileRoute } from '@tanstack/react-router'
import { FileUp, Loader2 } from 'lucide-react'
import { useState } from 'react'
import { z } from 'zod'
import type { GlobalWeightResult } from '@/api/circuits'
import { GlobalWeightsResults } from '@/components/circuits/global-weights-dialog'
import { Checkbox } from '@/components/ui/checkbox'

const edgeSchema = z.object({
  source: z.string(),
  sourceSaeName: z.string(),
  sourceFeature: z.number().int().nonnegative(),
  target: z.string(),
  targetSaeName: z.string(),
  targetFeature: z.number().int().nonnegative(),
  kind: z.literal('inhibitory'),
  score: z.number().finite().nonnegative(),
  normalizedInhibitoryScore: z.number().finite().nonnegative(),
  delta: z.number().finite(),
  virtualWeight: z.number().finite(),
  muOn: z.number().finite(),
  muOff: z.number().finite(),
})

const resultSchema = z.object({
  schemaVersion: z.literal(1),
  mode: z.literal('inhibitory'),
  datasetName: z.string(),
  shardIndex: z.number().int().nonnegative(),
  numShards: z.number().int().positive(),
  maxSamples: z.number().int().nonnegative(),
  saeSetName: z.string(),
  target: z.object({
    saeName: z.string(),
    featureIndex: z.number().int().nonnegative(),
  }),
  numSamples: z.number().int().positive(),
  numPositions: z.number().int().positive(),
  upstream: z.array(edgeSchema),
  downstream: z.array(edgeSchema).length(0),
})

export const Route = createFileRoute('/global-weights')({
  component: GlobalWeightsPage,
})

function GlobalWeightsPage() {
  const [result, setResult] = useState<GlobalWeightResult | null>(null)
  const [datasetName, setDatasetName] = useState('')
  const [saeSetName, setSaeSetName] = useState('')
  const [shard, setShard] = useState('')
  const [filename, setFilename] = useState('')
  const [normalized, setNormalized] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function readResult(file: File) {
    setLoading(true)
    setError(null)
    try {
      const parsed = resultSchema.parse(JSON.parse(await file.text()))
      setResult(parsed)
      setDatasetName(parsed.datasetName)
      setSaeSetName(parsed.saeSetName)
      setShard(`${parsed.shardIndex + 1}/${parsed.numShards}`)
      setFilename(file.name)
    } catch (cause) {
      setResult(null)
      setError(cause instanceof Error ? cause.message : 'Invalid result file')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-8 space-y-6">
      <header className="flex flex-wrap items-end justify-between gap-4 border-b pb-5">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold text-slate-900">
            Global weights
          </h1>
          {result && (
            <p className="text-sm text-slate-600 break-all">
              {result.target.saeName} #{result.target.featureIndex} ·{' '}
              {datasetName} · shard {shard} · {saeSetName}
            </p>
          )}
        </div>
        <label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border bg-white px-4 text-sm font-medium text-slate-700 hover:bg-slate-50">
          {loading ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <FileUp className="h-4 w-4" />
          )}
          Open result JSON
          <input
            type="file"
            accept="application/json,.json"
            className="sr-only"
            onChange={(event) => {
              const file = event.target.files?.[0]
              if (file) void readResult(file)
              event.target.value = ''
            }}
          />
        </label>
      </header>

      {error && (
        <p role="alert" className="text-sm text-red-600 break-words">
          {error}
        </p>
      )}
      {result ? (
        <>
          <div className="flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600">
            <span className="break-all">{filename}</span>
            <label className="flex items-center gap-2 cursor-pointer">
              <Checkbox
                checked={normalized}
                onCheckedChange={(value) => setNormalized(value === true)}
              />
              Normalize score
            </label>
          </div>
          <GlobalWeightsResults result={result} normalized={normalized} />
        </>
      ) : (
        !error && (
          <div className="py-20 text-center text-sm text-slate-500">
            Open a result generated by the inhibitory-global-weights command.
          </div>
        )
      )}
    </div>
  )
}
